---
sudo: false
language: python

env:
  matrix:
    - DJANGO=Django==3.2.11

python:
  - '3.7'
  - '3.8'
  - '3.9'

before_install:
  - pip install codecov

install:
  - pip install --pre $DJANGO
  - pip install -e .[test]

script:
  - py.test --cov=django_postcode_lookup --cov-report=term-missing

after_success:
  - codecov
